title: One plot a day, keep the doctor away
author: AD Ozbkir
email: aozb@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I will try to publish one vis of an interesting data, per day.
  Such a challange :)

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
